import { defineStore } from 'pinia';
import { GameStatus, type Game } from 'src/models/Game';
import { RosterId, SeasonId, TeamId, UserId, VenueId, LogoId, TeamGuid, LeagueId, LeagueGuid } from 'src/models/ids';
import { TimeString } from 'src/models/types/timeString';
import { TimeString as TimeUtil } from 'src/models/types/timeString';
import type { User } from 'src/models/User';
import type { Roster } from 'src/models/Roster';
import type { Team} from 'src/models/Team';
import type { Venue } from 'src/models/Venue';
import type { League } from 'src/models/League';

export const useScheduleStore = defineStore('schedule', {
  state: () => ({
    logos: [] as { id: LogoId, src: string }[],
    games: [] as Game[],
  }),
  actions: {
    loadExampleData() {
      this.logos = [
        { id: 'logo1' as unknown as LogoId, src: 'src/assets/test/homeys.png' },
        { id: 'logo2' as unknown as LogoId, src: 'src/assets/test/awaygoodteam.png' }
      ];
      this.games = [
        {
          id: 1,
          season_id: 'season1' as unknown as SeasonId,
          start: TimeUtil.fromString('2024-01-25T21:00:00Z') as TimeString,
          venue: {
            id: 1,
            name: 'Main Arena',
            location: '123 Arena St.',
            capacity: 5000,
            address: '123 Arena St., City, State, Zip',
            locker_rooms: ['A1', 'B1'],
            created_at: TimeUtil.fromString('2020-01-01T00:00:00Z') as TimeString,
            updated_at: TimeUtil.fromString('2020-01-01T00:00:00Z') as TimeString,
          } as Venue,
          venue_id: 1 as unknown as VenueId,
          status: GameStatus.SCHEDULED,
          home_team: {
            id: 1,
            team_guid: 'teamGuid1' as unknown as TeamGuid,
            name: 'The Homeboys',
            logo_id: 'logo1' as unknown as LogoId,
            color: 'blue',
            league_record_id: 'league1' as unknown as LeagueId,
            league_record: {
              id: 1,
              league_guid: 'league1' as unknown as LeagueGuid,
              wins: 10,
              losses: 2,
              ties: 1,
            } as unknown as League,
            roster: {
              id: 1,
              players: [
                {
                  id: 1,
                  first_name: 'John',
                  last_name: 'Doe',
                  email: 'john.doe@example.com',
                  phone: '123-456-7890',
                  roles: [],
                  skill_level: 5,
                  current_teams: [],
                  dob: TimeUtil.fromString('1990-01-01') as TimeString,
                } as unknown as User,
              ],
              captain: {
                id: 2,
                first_name: 'Jane',
                last_name: 'Smith',
                email: 'jane.smith@example.com',
                phone: '098-765-4321',
                roles: [],
                skill_level: 6,
                current_teams: [],
                dob: TimeUtil.fromString('1992-02-02') as TimeString,
              } as unknown as User,
              captain_id: 2 as unknown as UserId,
            } as unknown as Roster,
            roster_id: 1 as unknown as RosterId,
            wins: 10,
            losses: 2,
          } as unknown as Team,
          home_team_id: 1 as unknown as TeamId,
          home_team_roster: {
            id: 1,
            players: [
              {
                id: 1,
                first_name: 'John',
                last_name: 'Doe',
                email: 'john.doe@example.com',
                phone: '123-456-7890',
                roles: [],
                skill_level: 5,
                current_teams: [],
                dob: TimeUtil.fromString('1990-01-01') as TimeString,
              },
            ],
            captain: {
              id: 2,
              first_name: 'Jane',
              last_name: 'Smith',
              email: 'jane.smith@example.com',
              phone: '098-765-4321',
              roles: [],
              skill_level: 6,
              current_teams: [],
              dob: TimeUtil.fromString('1992-02-02') as TimeString,
            },
            captain_id: 2 as unknown as UserId,
          } as unknown as Roster,
          home_team_roster_id: 1 as unknown as RosterId,
          home_team_locker_room: 'A1',
          home_team_shots_on_goal: 10,
          home_team_score: 2,
          away_team: {
            id: 2,
            team_guid: 'teamGuid2' as unknown as TeamGuid,
            name: 'A Way Good Team',
            logo_id: 'logo2' as unknown as LogoId,
            color: 'red',
            league_record_id: 'league2' as unknown as LeagueId,
            league_record: {
              id: 2,
              league_guid: 'league2' as unknown as LeagueGuid,
              wins: 8,
              losses: 4,
              ties: 1,
            } as unknown as League,
            roster: {
              id: 2,
              players: [
                {
                  id: 3,
                  first_name: 'Alice',
                  last_name: 'Brown',
                  email: 'alice.brown@example.com',
                  phone: '321-654-0987',
                  roles: [],
                  skill_level: 4,
                  current_teams: [],
                  dob: TimeUtil.fromString('1988-03-03') as TimeString,
                } as unknown as User,
              ],
              captain: {
                id: 4,
                first_name: 'Bob',
                last_name: 'White',
                email: 'bob.white@example.com',
                phone: '987-654-3210',
                roles: [],
                skill_level: 7,
                current_teams: [],
                dob: TimeUtil.fromString('1985-04-04') as TimeString,
              } as unknown as User,
              captain_id: 4 as unknown as UserId,
            } as unknown as Roster,
            roster_id: 2 as unknown as RosterId,
            wins: 8,
            losses: 4,
          } as unknown as Team,
          away_team_id: 2 as unknown as TeamId,
          away_team_roster: {
            id: 2,
            players: [
              {
                id: 3 as unknown as UserId,
                first_name: 'Alice',
                last_name: 'Brown',
                email: 'alice.brown@example.com',
                phone: '321-654-0987',
                roles: [],
                skill_level: 4,
                current_teams: [],
                dob: TimeUtil.fromString('1988-03-03') as TimeString,
              },
            ],
            captain: {
              id: 4 as unknown as UserId,
              first_name: 'Bob',
              last_name: 'White',
              email: 'bob.white@example.com',
              phone: '987-654-3210',
              roles: [],
              skill_level: 7,
              current_teams: [],
              dob: TimeUtil.fromString('1985-04-04') as TimeString,
            },
            captain_id: 4 as unknown as UserId,
          } as unknown as Roster,
          away_team_roster_id: 2 as unknown as RosterId,
          away_team_locker_room: 'B1',
          away_team_shots_on_goal: 8,
          away_team_score: 1,
          score_keeper: {
            id: 5,
            first_name: 'Charlie',
            last_name: 'Green',
            email: 'charlie.green@example.com',
            phone: '555-555-5555',
            roles: [],
            skill_level: 3,
            current_teams: [],
            dob: TimeUtil.fromString('1975-05-05') as TimeString,
          },
          score_keeper_id: 5 as unknown as UserId,
          primary_referee: {
            id: 6,
            first_name: 'Dave',
            last_name: 'Blue',
            email: 'dave.blue@example.com',
            phone: '444-444-4444',
            roles: [],
            skill_level: 5,
            current_teams: [],
            dob: TimeUtil.fromString('1980-06-06') as TimeString,
          } as unknown as User,
          primary_referee_id: 6 as unknown as UserId,
          secondary_referee: {
            id: 7,
            first_name: 'Eve',
            last_name: 'Red',
            email: 'eve.red@example.com',
            phone: '333-333-3333',
            roles: [],
            skill_level: 4,
            current_teams: [],
            dob: TimeUtil.fromString('1983-07-07') as TimeString,
          } as unknown as User,
          secondary_referee_id: 7 as unknown as UserId,
        } as unknown as Game,
        {
          id: 2,
          season_id: 'season1' as unknown as SeasonId,
          start: TimeUtil.fromString('2024-02-01T19:00:00Z') as TimeString,
          venue: {
            id: 2,
            name: 'Secondary Arena',
            location: '456 Secondary St.',
            capacity: 3000,
            address: '456 Secondary St., City, State, Zip',
            locker_rooms: ['C1', 'D1'],
            created_at: TimeUtil.fromString('2020-02-01T00:00:00Z') as TimeString,
            updated_at: TimeUtil.fromString('2020-02-01T00:00:00Z') as TimeString,
          } as Venue,
          venue_id: 2 as unknown as VenueId,
          status: GameStatus.SCHEDULED,
          home_team: {
            id: 3,
            team_guid: 'teamGuid3' as unknown as TeamGuid,
            name: 'Another Home Team',
            logo_id: 'logo1' as unknown as LogoId,
            color: 'green',
            league_record_id: 'league3' as unknown as LeagueId,
            league_record: {
              id: 3,
              league_guid: 'league3' as unknown as LeagueGuid,
              wins: 5,
              losses: 5,
              ties: 0,
            } as unknown as League,
            roster: {
              id: 3,
              players: [
                {
                  id: 1,
                  first_name: 'John',
                  last_name: 'Doe',
                  email: 'john.doe@example.com',
                  phone: '123-456-7890',
                  roles: [],
                  skill_level: 5,
                  current_teams: [],
                  dob: TimeUtil.fromString('1990-01-01') as TimeString,
                } as unknown as User,
                {
                  id: 3,
                  first_name: 'Alice',
                  last_name: 'Brown',
                  email: 'alice.brown@example.com',
                  phone: '321-654-0987',
                  roles: [],
                  skill_level: 4,
                  current_teams: [],
                  dob: TimeUtil.fromString('1988-03-03') as TimeString,
                } as unknown as User,
              ],
              captain: {
                id: 2,
                first_name: 'Jane',
                last_name: 'Smith',
                email: 'jane.smith@example.com',
                phone: '098-765-4321',
                roles: [],
                skill_level: 6,
                current_teams: [],
                dob: TimeUtil.fromString('1992-02-02') as TimeString,
              } as unknown as User,
              captain_id: 2 as unknown as UserId,
            } as unknown as Roster,
            roster_id: 3 as unknown as RosterId,
            wins: 5,
            losses: 5,
          } as unknown as Team,
          home_team_id: 3 as unknown as TeamId,
          home_team_roster: {
            id: 3,
            players: [
              {
                id: 1,
                first_name: 'John',
                last_name: 'Doe',
                email: 'john.doe@example.com',
                phone: '123-456-7890',
                roles: [],
                skill_level: 5,
                current_teams: [],
                dob: TimeUtil.fromString('1990-01-01') as TimeString,
              },
              {
                id: 3,
                first_name: 'Alice',
                last_name: 'Brown',
                email: 'alice.brown@example.com',
                phone: '321-654-0987',
                roles: [],
                skill_level: 4,
                current_teams: [],
                dob: TimeUtil.fromString('1988-03-03') as TimeString,
              },
            ],
            captain: {
              id: 2,
              first_name: 'Jane',
              last_name: 'Smith',
              email: 'jane.smith@example.com',
              phone: '098-765-4321',
              roles: [],
              skill_level: 6,
              current_teams: [],
              dob: TimeUtil.fromString('1992-02-02') as TimeString,
            },
            captain_id: 2 as unknown as UserId,
          } as unknown as Roster,
          home_team_roster_id: 3 as unknown as RosterId,
          home_team_locker_room: 'C1',
          home_team_shots_on_goal: 15,
          home_team_score: 1,
          away_team: {
            id: 4,
            team_guid: 'teamGuid4' as unknown as TeamGuid,
            name: 'Yet Another Away Team',
            logo_id: 'logo2' as unknown as LogoId,
            color: 'yellow',
            league_record_id: 'league4' as unknown as LeagueId,
            league_record: {
              id: 4,
              league_guid: 'league4' as unknown as LeagueGuid,
              wins: 6,
              losses: 4,
              ties: 1,
            } as unknown as League,
            roster: {
              id: 4,
              players: [
                {
                  id: 4,
                  first_name: 'Bob',
                  last_name: 'White',
                  email: 'bob.white@example.com',
                  phone: '987-654-3210',
                  roles: [],
                  skill_level: 7,
                  current_teams: [],
                  dob: TimeUtil.fromString('1985-04-04') as TimeString,
                } as unknown as User,
                {
                  id: 5,
                  first_name: 'Charlie',
                  last_name: 'Green',
                  email: 'charlie.green@example.com',
                  phone: '555-555-5555',
                  roles: [],
                  skill_level: 3,
                  current_teams: [],
                  dob: TimeUtil.fromString('1975-05-05') as TimeString,
                } as unknown as User,
              ],
              captain: {
                id: 4,
                first_name: 'Bob',
                last_name: 'White',
                email: 'bob.white@example.com',
                phone: '987-654-3210',
                roles: [],
                skill_level: 7,
                current_teams: [],
                dob: TimeUtil.fromString('1985-04-04') as TimeString,
              } as unknown as User,
              captain_id: 4 as unknown as UserId,
            } as unknown as Roster,
            roster_id: 4 as unknown as RosterId,
            wins: 6,
            losses: 4,
          } as unknown as Team,
          away_team_id: 4 as unknown as TeamId,
          away_team_roster: {
            id: 4,
            players: [
              {
                id: 4 as unknown as UserId,
                first_name: 'Bob',
                last_name: 'White',
                email: 'bob.white@example.com',
                phone: '987-654-3210',
                roles: [],
                skill_level: 7,
                current_teams: [],
                dob: TimeUtil.fromString('1985-04-04') as TimeString,
              },
              {
                id: 5 as unknown as UserId,
                first_name: 'Charlie',
                last_name: 'Green',
                email: 'charlie.green@example.com',
                phone: '555-555-5555',
                roles: [],
                skill_level: 3,
                current_teams: [],
                dob: TimeUtil.fromString('1975-05-05') as TimeString,
              },
            ],
            captain: {
              id: 4 as unknown as UserId,
              first_name: 'Bob',
              last_name: 'White',
              email: 'bob.white@example.com',
              phone: '987-654-3210',
              roles: [],
              skill_level: 7,
              current_teams: [],
              dob: TimeUtil.fromString('1985-04-04') as TimeString,
            },
            captain_id: 4 as unknown as UserId,
          } as unknown as Roster,
          away_team_roster_id: 4 as unknown as RosterId,
          away_team_locker_room: 'D1',
          away_team_shots_on_goal: 10,
          away_team_score: 2,
          score_keeper: {
            id: 6,
            first_name: 'Dave',
            last_name: 'Blue',
            email: 'dave.blue@example.com',
            phone: '444-444-4444',
            roles: [],
            skill_level: 5,
            current_teams: [],
            dob: TimeUtil.fromString('1980-06-06') as TimeString,
          },
          score_keeper_id: 6 as unknown as UserId,
          primary_referee: {
            id: 7,
            first_name: 'Eve',
            last_name: 'Red',
            email: 'eve.red@example.com',
            phone: '333-333-3333',
            roles: [],
            skill_level: 4,
            current_teams: [],
            dob: TimeUtil.fromString('1983-07-07') as TimeString,
          } as unknown as User,
          primary_referee_id: 7 as unknown as UserId,
          secondary_referee: {
            id: 5,
            first_name: 'Charlie',
            last_name: 'Green',
            email: 'charlie.green@example.com',
            phone: '555-555-5555',
            roles: [],
            skill_level: 3,
            current_teams: [],
            dob: TimeUtil.fromString('1975-05-05') as TimeString,
          } as unknown as User,
          secondary_referee_id: 5 as unknown as UserId,
        } as unknown as Game,
      ];
    },
  },
});
