parameters:
  OffsetParam:
    in: query
    name: offset
    schema:
      type: integer
    description: The number of items to skip before starting to collect the result set (defaults to 0)

  LimitParam:
    in: query
    name: limit
    schema:
      type: integer
    description: The numbers of items to return (defaults to 10)

  FetchAllParam:
    in: query
    name: fetch_all
    schema:
      type: boolean
    description: Fetch all leagues (ignores offset / limit)

  SortFieldParam:
    in: query
    name: sort_field
    schema:
      type: string
    description: Field to sort on (defaults to ID)

  SortOrderParam:
    in: query
    name: sort_order
    schema:
      type: string
    description: Order in which to sort (defaults to ASC)
    enum: [ASC, DESC]
