// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package components

import (
	"github.com/jak103/powerplay/internal/models"
	"sync"
)

// Ensure, that sessionMock does implement session.
// If this is not the case, regenerate this file with moq.
var _ session = &sessionMock{}

// sessionMock is a mock implementation of session.
//
//	func TestSomethingThatUsessession(t *testing.T) {
//
//		// make and configure a mocked session
//		mockedsession := &sessionMock{
//			CreateSeasonFunc: func(goal *models.Season) (*models.Season, error) {
//				panic("mock out the CreateSeason method")
//			},
//			GetSeasonsFunc: func() ([]models.Season, error) {
//				panic("mock out the GetSeasons method")
//			},
//		}
//
//		// use mockedsession in code that requires session
//		// and then make assertions.
//
//	}
type sessionMock struct {
	// CreateSeasonFunc mocks the CreateSeason method.
	CreateSeasonFunc func(goal *models.Season) (*models.Season, error)

	// GetSeasonsFunc mocks the GetSeasons method.
	GetSeasonsFunc func() ([]models.Season, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSeason holds details about calls to the CreateSeason method.
		CreateSeason []struct {
			// Goal is the goal argument value.
			Goal *models.Season
		}
		// GetSeasons holds details about calls to the GetSeasons method.
		GetSeasons []struct {
		}
	}
	lockCreateSeason sync.RWMutex
	lockGetSeasons   sync.RWMutex
}

// CreateSeason calls CreateSeasonFunc.
func (mock *sessionMock) CreateSeason(goal *models.Season) (*models.Season, error) {
	if mock.CreateSeasonFunc == nil {
		panic("sessionMock.CreateSeasonFunc: method is nil but session.CreateSeason was just called")
	}
	callInfo := struct {
		Goal *models.Season
	}{
		Goal: goal,
	}
	mock.lockCreateSeason.Lock()
	mock.calls.CreateSeason = append(mock.calls.CreateSeason, callInfo)
	mock.lockCreateSeason.Unlock()
	return mock.CreateSeasonFunc(goal)
}

// CreateSeasonCalls gets all the calls that were made to CreateSeason.
// Check the length with:
//
//	len(mockedsession.CreateSeasonCalls())
func (mock *sessionMock) CreateSeasonCalls() []struct {
	Goal *models.Season
} {
	var calls []struct {
		Goal *models.Season
	}
	mock.lockCreateSeason.RLock()
	calls = mock.calls.CreateSeason
	mock.lockCreateSeason.RUnlock()
	return calls
}

// GetSeasons calls GetSeasonsFunc.
func (mock *sessionMock) GetSeasons() ([]models.Season, error) {
	if mock.GetSeasonsFunc == nil {
		panic("sessionMock.GetSeasonsFunc: method is nil but session.GetSeasons was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetSeasons.Lock()
	mock.calls.GetSeasons = append(mock.calls.GetSeasons, callInfo)
	mock.lockGetSeasons.Unlock()
	return mock.GetSeasonsFunc()
}

// GetSeasonsCalls gets all the calls that were made to GetSeasons.
// Check the length with:
//
//	len(mockedsession.GetSeasonsCalls())
func (mock *sessionMock) GetSeasonsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetSeasons.RLock()
	calls = mock.calls.GetSeasons
	mock.lockGetSeasons.RUnlock()
	return calls
}
